/**
 * The Editor - Backend Entrypoint
 * 
 * This agent generates daily briefings by synthesizing journal entries,
 * GitHub commits, and web search results.
 */

const { rpc } = global;

/**
 * Get today's date in YYYY-MM-DD format
 */
function getToday() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

/**
 * Lifecycle hook: called when the plugin is started
 */
async function main() {
  console.log('[Editor] Plugin starting...');

  try {
    // Register daily briefing at 8:00 AM
    await rpc.scheduler.register('0 8 * * *', 'daily-briefing');
    console.log('[Editor] Registered daily briefing scheduler');
  } catch (error) {
    console.error('[Editor] Failed to register scheduler:', error.message);
  }
}

/**
 * Event handler: called by the shell when a registered cron fires
 * @param {string} handlerId The ID provided during registration
 */
global.onSchedulerEvent = async (handlerId) => {
  console.log(`[Editor] Received scheduler event: ${handlerId}`);
  
  if (handlerId === 'daily-briefing') {
    await generateDailyBriefing();
  }
};

/**
 * Generate the daily briefing by synthesizing multiple data sources
 */
async function generateDailyBriefing() {
  const today = getToday();
  console.log(`[Editor] Generating briefing for ${today}`);

  try {
    // 1. Load journal entry
    const journal = await rpc.store.get(`journal_${today}`) || 'No journal entry for today.';
    console.log('[Editor] Loaded journal');

    // 2. Fetch GitHub commits
    const commits = await rpc.mcp.call('github', 'get_commits', { since: '24h' });
    console.log(`[Editor] Fetched ${commits.length} commits`);

    // 3. Fetch web search results
    const searchResults = await rpc.mcp.call('brave-search', 'search', { q: '.NET 9 features' });
    console.log(`[Editor] Fetched ${searchResults.length} search results`);

    // 4. Synthesize the briefing (simulated LLM)
    const briefing = synthesizeBriefing(journal, commits, searchResults);

    // 5. Save the briefing
    await rpc.store.set(`briefing_${today}`, briefing);
    console.log('[Editor] Saved briefing');

    // 6. Notify the user
    await rpc.notify.send('info', 'Your Daily Briefing is ready!');
  } catch (error) {
    console.error('[Editor] Briefing generation failed:', error.message);
    await rpc.notify.send('error', 'Failed to generate Daily Briefing');
  }
}

/**
 * Simulate LLM synthesis of multiple data sources
 */
function synthesizeBriefing(journal, commits, searchResults) {
  const commitList = commits.map(c => `- ${c.message} (${c.sha.substring(0, 7)})`).join('\n');
  const searchList = searchResults.map(s => `- [${s.title}](${s.url})`).join('\n');

  return `# Daily Briefing - ${getToday()}

## 📝 Your Journal Entry
${journal}

## 🔧 Recent GitHub Activity
${commitList || 'No recent commits.'}

## 🌐 Trending Topics
${searchList || 'No search results.'}

---
*Generated by The Editor*
`;
}

// Start the plugin
main().catch(err => console.error('[Editor] Main error:', err));
